### Create a payment
POST http://localhost:3000/payments
Content-Type: application/json

{
  "reservationId": "8d783e1f-3161-49bd-bf31-6081bd3c85ba",
  "method": "visa",
  "cardNumber": "4111111111111111",
  "cardHolder": "John Doe"
}

### Refund a payment
POST http://localhost:3000/payments/refund
Content-Type: application/json

{
  "paymentId": "55bab047-1ff9-48b2-8365-8385a39bd560",
  "amount": 90.00,
  "reason": "Cancelled event"
}

### Get my payments
GET http://localhost:3000/payments

### Get payment by id
GET http://localhost:3000/payments/55bab047-1ff9-48b2-8365-8385a39bd560
