### 🔒 Lock seats
POST http://localhost:3000/reservations/lock
Content-Type: application/json

{
  "eventId": "b1f5d3c4-1234-4f2e-9876-abcdef123456",
  "seatIds": ["A10"]
}

###


### ✅ Confirm reservation
PATCH http://localhost:3000/reservations/8cb441a0-ab6b-4562-bf92-51d0af21d0bd/confirm
Content-Type: application/json

###

### ❌ Cancel reservation
PATCH http://localhost:3000/reservations/cfaf6d56-2f4d-49dc-ab5b-bb2df133d109/cancel
Content-Type: application/json

###

### 🔍 Get reservation by ID
GET http://localhost:3000/reservations/3493966a-4cc0-4e69-8770-5dcd5563af63
Content-Type: application/json

###

### 👤 Get reservations by user
GET http://localhost:3000/reservations/user/sample-user-id
Content-Type: application/json

